#- name: users | remove root user from hosts
#  mysql_user: >
#    name=root
#    host={{ item }}
#    state=absent
#  with_items:
#    - "{{ ansible_hostname }}"
#    - ansible_fqdn
#    - 127.0.0.1
#    - ::1
#    #- localhost

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: users | update root password for all hosts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ mysql.root_password|default('') }}
    priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: users | add root credentials
  template: >
    src=common/my.user.cnf.j2
    dest=/root/.my.cnf
    owner=root
    mode=0600
  notify:
    - mysql-restart

- name: users | add user credentials
  template: >
    src=common/my.user.cnf.j2
    dest={{ ansible_env.HOME }}/.my.cnf
    owner={{ ansible_env.USER }}
    mode=0600
  notify:
    - mysql-restart

- name: users | remove anonymous user
  mysql_user: >
    name=''
    host={{ item }}
    state=absent
  with_items:
    - "{{ ansible_fqdn }}"
    - localhost

# TODO : priv={{ item.name }}:{{ item.grant }}
# priv=*.*:ALL host='%'
- name: users | install all users
  mysql_user: >
    name={{ item.user }}
    password={{ item.password }}
    host={{ item.host }}
    priv=*.*:{{ item.grant|join(',') }}
    state=present
  with_items: mysql.databases
  when: mysql.databases is defined
