- name: mysql-restart
  service: >
    name={{ service_mysql }}
    state=restarted

- name: mysql-start
  service: >
    name={{ service_mysql }} 
    state=started
    enabled=true

- name: mysql-stop
  service: >
    name={{ service_mysql }} 
    state=stopped
